let sampleQuestions = [
  {
    question: "What is the speed of light?",
    category: "Physics",
    sub_category: "Waves",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Who proposed the theory of relativity?",
    category: "Physics",
    sub_category: "Relativity",
    difficulty: "Medium",
    points: 10,
  },
  {
    question: "What is the chemical symbol for gold?",
    category: "Chemistry",
    sub_category: "Elements",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "In which year did Christopher Columbus reach the Americas?",
    category: "History",
    sub_category: "Exploration",
    difficulty: "Medium",
    points: 8,
  },
  {
    question: "What is the capital of France?",
    category: "Geography",
    sub_category: "World Capitals",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Who wrote 'Romeo and Juliet'?",
    category: "Literature",
    sub_category: "Drama",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the largest planet in our solar system?",
    category: "Astronomy",
    sub_category: "Planets",
    difficulty: "Easy",
    points: 6,
  },
  {
    question: "What is the formula for calculating the area of a circle?",
    category: "Mathematics",
    sub_category: "Geometry",
    difficulty: "Medium",
    points: 8,
  },
  {
    question: "Who was the first President of the United States?",
    category: "History",
    sub_category: "Presidents",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "What is the powerhouse of the cell?",
    category: "Biology",
    sub_category: "Cell Biology",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "In which year did the Titanic sink?",
    category: "History",
    sub_category: "Maritime Disasters",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "Who painted the Mona Lisa?",
    category: "Art",
    sub_category: "Painting",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the currency of Japan?",
    category: "Geography",
    sub_category: "Currencies",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "What is the boiling point of water in Celsius?",
    category: "Chemistry",
    sub_category: "Physical Properties",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Who developed the theory of evolution by natural selection?",
    category: "Biology",
    sub_category: "Evolution",
    difficulty: "Medium",
    points: 8,
  },
  {
    question: "What is the largest mammal on Earth?",
    category: "Biology",
    sub_category: "Mammals",
    difficulty: "Easy",
    points: 6,
  },
  {
    question: "Which gas is responsible for the Earth's greenhhouse effect?",
    category: "Environmental Science",
    sub_category: "Atmosphere",
    difficulty: "Medium",
    points: 8,
  },
  {
    question: "Who is known as the 'Father of Computing'?",
    category: "Computer Science",
    sub_category: "Pioneers",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the largest ocean on Earth?",
    category: "Geography",
    sub_category: "Oceans",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Who wrote 'To Kill a Mockingbird'?",
    category: "Literature",
    sub_category: "Novels",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the square root of 64?",
    category: "Mathematics",
    sub_category: "Arithmetic",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Which planet is known as the 'Red Planet'?",
    category: "Astronomy",
    sub_category: "Planets",
    difficulty: "Easy",
    points: 6,
  },
  {
    question: "Who discovered penicillin?",
    category: "Medicine",
    sub_category: "Antibiotics",
    difficulty: "Medium",
    points: 8,
  },
  {
    question: "What is the capital of Australia?",
    category: "Geography",
    sub_category: "World Capitals",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Who painted 'Starry Night'?",
    category: "Art",
    sub_category: "Painting",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the chemical symbol for water?",
    category: "Chemistry",
    sub_category: "Molecules",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "In which year did World War II end?",
    category: "History",
    sub_category: "World Wars",
    difficulty: "Medium",
    points: 8,
  },
  {
    question: "Who wrote '1984'?",
    category: "Literature",
    sub_category: "Dystopian Fiction",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the formula for the area of a rectangle?",
    category: "Mathematics",
    sub_category: "Geometry",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Who is known as the 'Queen of Pop'?",
    category: "Music",
    sub_category: "Pop Music",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the smallest prime number?",
    category: "Mathematics",
    sub_category: "Number Theory",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Who wrote 'The Great Gatsby'?",
    category: "Literature",
    sub_category: "Novels",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the capital of Brazil?",
    category: "Geography",
    sub_category: "World Capitals",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Which element has the chemical symbol 'Na'?",
    category: "Chemistry",
    sub_category: "Elements",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "In which year did the American Civil War end?",
    category: "History",
    sub_category: "Civil War",
    difficulty: "Medium",
    points: 8,
  },
  {
    question: "Who directed the movie 'Inception'?",
    category: "Film",
    sub_category: "Directors",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the largest desert in the world?",
    category: "Geography",
    sub_category: "Deserts",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Who is the author of 'The Catcher in the Rye'?",
    category: "Literature",
    sub_category: "Novels",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the chemical symbol for iron?",
    category: "Chemistry",
    sub_category: "Elements",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "In which year did the Berlin Wall fall?",
    category: "History",
    sub_category: "Cold War",
    difficulty: "Medium",
    points: 8,
  },
  {
    question: "Who played the character of Jack Dawson in the movie 'Titanic'?",
    category: "Film",
    sub_category: "Actors",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the capital of China?",
    category: "Geography",
    sub_category: "World Capitals",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Which planet is known as the 'Blue Planet'?",
    category: "Astronomy",
    sub_category: "Planets",
    difficulty: "Easy",
    points: 6,
  },
  {
    question: "Who wrote 'Pride and Prejudice'?",
    category: "Literature",
    sub_category: "Novels",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the largest mammal in the ocean?",
    category: "Biology",
    sub_category: "Marine Life",
    difficulty: "Easy",
    points: 6,
  },
  {
    question: "Which gas is responsible for the color of the Earth's sky?",
    category: "Environmental Science",
    sub_category: "Atmosphere",
    difficulty: "Medium",
    points: 8,
  },
  {
    question: "Who is the inventor of the telephone?",
    category: "Technology",
    sub_category: "Inventions",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the currency of South Africa?",
    category: "Geography",
    sub_category: "Currencies",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Who painted 'The Persistence of Memory'?",
    category: "Art",
    sub_category: "Painting",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the chemical symbol for silver?",
    category: "Chemistry",
    sub_category: "Elements",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "In which year did the Industrial Revolution begin?",
    category: "History",
    sub_category: "Industrial Revolution",
    difficulty: "Medium",
    points: 8,
  },
  {
    question: "Who wrote 'The Hobbit'?",
    category: "Literature",
    sub_category: "Fantasy",
    difficulty: "Medium",
    points: 7,
  },
  {
    question: "What is the cube of 3?",
    category: "Mathematics",
    sub_category: "Arithmetic",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Which moon is the largest in our solar system?",
    category: "Astronomy",
    sub_category: "Moons",
    difficulty: "Easy",
    points: 6,
  },
  {
    question: "Who discovered the circulation of blood in the human body?",
    category: "Medicine",
    sub_category: "Medical Discoveries",
    difficulty: "Medium",
    points: 8,
  },
  {
    question: "What is the capital of Mexico?",
    category: "Geography",
    sub_category: "World Capitals",
    difficulty: "Easy",
    points: 5,
  },
  {
    question: "Who created the sculpture 'David'?",
    category: "Art",
    sub_category: "Sculpture",
    difficulty: "Medium",
    points: 7,
  },
];

module.exports = sampleQuestions;
